namespace OpenFinanceWebApi.Models
{
    public class ReportRequest
    {
        public string? FromDate { get; set; }
        public string? ToDate { get; set; }
        public string? RefNo { get; set; }
        public string? Amount { get; set; }
        public string? BeneficiaryBank { get; set; }
        public string? CusIban { get; set; }
        public string? debtorIban { get; set; }
        public string? reportType { get; set; }
        public string? FileName { get; set; }
        public string? CatPurposeCode { get; set; }
        public string? UserID { get; set; }
        public string? Username { get; set; }
        public string? EmailId { get; set; }
        public string? userProductname { get; set; }
        public string? RoleID { get; set; }
        public string? RoleName { get; set; }
        public string? RoleDescription { get; set; }
        public string? Transactionname { get; set; }
        public string? OriginalRefNO { get; set; }
        public string? ReturnRefNO { get; set; }
        public string? Transactionprocesstype { get; set; }
        public string? Transactiontype { get; set; }
        public string? Postingtype { get; set; }
        public string? Postingstatus { get; set; }
        public string? BankName { get; set; }
        public string? IBAN { get; set; }
        public string? CurrencyCode { get; set; }
        public string? TransType { get; set; }
        public string? SenderIBan { get; set; }
        public string? RecipientIBAN { get; set; }
        public string? PaymentType { get; set; }
        public string? RequestPay { get; set; }
        public string? OriginatorReference { get; set; }
        public string? SettlementDateFrom { get; set; }
        public string? SettlementDateTo { get; set; }
        public string? Currency { get; set; }
        public string? SenderReference { get; set; }
        public string? SystemReference { get; set; }
        public string? Payer { get; set; }
        public string? BatchSystemReference { get; set; }
        public string? Beneficiary { get; set; }
        public string? MessageReference { get; set; }
        public string? Source { get; set; }
        public string? Status { get; set; }
        public string? SettlementCycle { get; set; }
        public string? AccountHolder { get; set; }
        public string? Participant { get; set; }
        public string? Product { get; set; }
        public string? Messagetype { get; set; }
        public string? Account { get; set; }
        public string? Date { get; set; }
        public string? Refrence_ID { get; set; }
        public string? AccountHolderBic { get; set; }
        public string? AccountNumber { get; set; }
        public string? DateTime { get; set; }
        public string? Datasource { get; set; }
        public string? CycleNumber { get; set; }
        public string? Liquidity_Type { get; set; }
        public string? Bic { get; set; }
        public string? Timestamp { get; set; }
        public string? limit { get; set; }
        public string? AvailableAmount { get; set; }
        public string? Balance { get; set; }
        public string? Debits { get; set; }
        public string? Credits { get; set; }
        public string? Reserve { get; set; }
        public string? BankUserId { get; set; }
        public string? OperationType { get; set; }
        public string? Name { get; set; }
        public string? VatNumber { get; set; }
        public string? MobileNo { get; set; }
        public string? MerchantType { get; set; }
        public string? MerchantValue { get; set; }
        public string? ShopId { get; set; }
        public string? Customer_Surname { get; set; }
        public string? Customer_Currency { get; set; }
        public string? CustomerType { get; set; }
        public string? CustomerValue { get; set; }
        public string? Is_Deleted { get; set; }
        public string? is_active { get; set; }
        public string? Customer_IBAN { get; set; }
        public string? endtoendid { get; set; }
        public string? PacsID { get; set; }
        public string? Module { get; set; }
        public string? Payment { get; set; }
        public string? IsMatched { get; set; }
        public string? BeneficiaryBankName { get; set; }
        public string? Interbank_Settlement_Date { get; set; }
        public string? TransactionID { get; set; }
        public string? creditorIban { get; set; }
    }
}
